# this was coipied over from CS559-22 

locale = "en-us"
title = "CS559 Computer Graphics Tutorials"
# note that we are skipping "sp22" theme - we'll try to put it right in the site
# we switched from mainroad to roadster in 2025
theme = ["559Theme","roadster"]

# this is archaic - and deprecated in Fall of 2024
# this seems to make things more robust to different deployments
#baseURL = ""
#relativeURLs = true
#canonifyURLs = true
enableGitInfo = true

# unsafe, but useful...
enableInlineShortcodes = true

# this is just for testing...
staticDir = [ "static" ]

# a basic menu
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -1000

[Params]
post_meta = ["section","date","taglist","categories"]
mainSections = [""]
dateformat = "January 2, 2006"
copyright = "Michael Gleicher"
subtitle = "Tutorial Resources for CS559"
# archive = "Archive of the Spring 2023 Class"
# archivenote = "This web page is from the Spring 2023 CS559 (Computer Graphics) class."
ImportantPages = ["allpages"]
pagination.pagerSize = 15
themestyle = "new"
recentSections = ["posts","assigns", "weeks-in-vis","gallery"]

fixme = false

[Params.sidebar]
home = "right"
list = "right"
single = "right"
# remove "thisweek" - since it is irrelevant for CS559
widgets = ["section","lunr","important","links","sections","taglist"]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[security]
  allowContent = ["^text/markdown$", "^text/html$"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
